export const SEARCH_BY_KEYWORD = "SEARCH_BY_KEYWORD"
export const SEARCH_BY_KEYWORD_LOADING = "SEARCH_BY_KEYWORD_LOADING"
export const SEARCH_BY_KEYWORD_SUCCESS = "SEARCH_BY_KEYWORD_SUCCESS"
export const SEARCH_BY_KEYWORD_ERROR = "SEARCH_BY_KEYWORD_ERROR"

export const ADD_NEW_WORD = "ADD_NEW_WORD"
export const ADD_NEW_WORD_SUCCESS = "ADD_NEW_WORD_SUCCESS"
export const ADD_NEW_WORD_ERROR = "ADD_NEW_WORD_ERROR"

export const CLOSE_SEARCH = "CLOSE_SEARCH"
export const OPEN_SEARCH = "OPEN_SEARCH"